document.write("<div style='width:100%; height: 90px; border: 1px solid #ff0000; border-width:1px 0; clear: both; position: relative; overflow: hidden;background-color: #FEAFAF; font-family: Arial,Helvetica,Tahoma,sans-serif; font-size: 12px; color: #000;'>")
document.write("   <div style='width:728px; margin:0 auto'>")
document.write("       <div style='position: absolute; right: 3px; top: 1px; float: right;'>")
document.write("          <a style='color: #000;font-size: 16px;line-height: 16px;font-weight: bold;text-decoration: none;' onclick='javascript:this.parentNode.parentNode.parentNode.style.display=\"none\"; return false;' href='#'>")
document.write("               ×")
document.write("           </a>")
document.write("       </div>")
document.write("       <div style='margin-top: 7px; margin-bottom: 7px;'>")
document.write("           <div style='float: left; margin-top: 8px; width: 163px;'>")
document.write("               <img alt='ie6no' src='http://ie6no.org/images/ie6no-small.gif' style='border: none;' />")
document.write("           </div>")
document.write("           <div style='float: left; width: 281px; overflow: hidden;'>")
document.write("               <div style='font-weight: bold; text-align: center;'>注意！</div>")//www.netxu.com
document.write("               <div style='margin-top: 10px;'>")
document.write("                   您正在使用一款过时的浏览器，我们建议您升级到更先进的浏览器以获得更好的使用体验。")
document.write("               </div>")
document.write("           </div>")
document.write("           <div style='float: left; margin-left: 5px;'>")
document.write("               <a target='_blank' href='http://admin.sokobo.cn/soft/Chrome_setup_chs.exe'><img alt='Get Chrome' style='border: none;' src='http://ie6no.org/images/ie6no-chrome.jpg' /></a>")//http://www.netxu.com/thread-239-1-1.html
document.write("           </div>")
document.write("           <div style='float: left; margin-left: 7px;'>")
document.write("               <a target='_blank' href='http://www.firefox.com.cn/'><img alt='Get Firefox' style='border: none;' src='http://ie6no.org/images/ie6no-firefox.jpg' /></a>")
document.write("           </div>")
document.write("           <div style='float: left; margin-left: 5px;'>")
document.write("               <a target='_blank' href='http://admin.sokobo.cn/soft/IE10-Windows6.1-x86-zh-cn.exe'><img alt='Get IE' style='border: none;' src='http://ie6no.org/images/ie6no-ie.jpg' /></a>")
document.write("           </div>")
document.write("           <div style='float: left; margin-left: 5px;'>")
document.write("               <a target='_blank' href='http://admin.sokobo.cn/soft/SafariSetup.exe'><img alt='Get Safari' style='border: none;' src='http://ie6no.org/images/ie6no-safari.jpg' /></a>")//www.netxu.com
document.write("           </div>")

document.write("           <div style='float: left; margin-left: 5px; '>")
document.write("               <a target='_blank' href='http://www.opera.com/zh-cn'><img alt='Get Opera' style='border: none;' src='http://ie6no.org/images/ie6no-opera.jpg' /></a>")
document.write("           </div>")
document.write("       </div>")//www.netxu.com
document.write("   </div>")
document.write("</div>")
