// JavaScript Document
function drawTinyLine(chartId,width,height,data,color){var bpi=[];var first={dataLabels:{enabled:true,x:-12,y:5},y:parseInt(data[0])};bpi.push(first);for(var i=1;i<data.length-1;i++){bpi.push(parseInt(data[i]));}
var last={dataLabels:{enabled:true},y:parseInt(data[data.length-1]),marker:{enabled:true}};bpi.push(last);var lastColor=color?color:'#F6F7F8';var chart=new Highcharts.Chart({chart:{renderTo:chartId,height:height,width:width,margin:[0,25,0,25],type:'line',backgroundColor:lastColor},title:{text:''},xAxis:{endOnTick:false},yAxis:{title:{text:''},offset:50,max:2000,startOnTick:false,gridLineColor:lastColor,endOnTick:false},credits:{enabled:false},legend:{enabled:false},plotOptions:{series:{marker:{enabled:false,lineWidth:1,lineColor:'#000'}}},tooltip:{enabled:false},series:[{data:bpi,color:'#000',lineWidth:1}]});}
function drawPie(chartId,width,height,data,color){var i=0;for(var i in data){data[i][1]=Number(data[i][1],2);i++;}
var lastColor=color?color:'#F6F7F8';var chart=new Highcharts.Chart({chart:{renderTo:chartId,type:'pie',width:width,height:height,margin:[25,0,25,0],backgroundColor:lastColor},tooltip:{enabled:false,pointFormat:'<b>{point.percentage}%</b>',percentageDecimals:1},title:{text:''},credits:{enabled:false},series:[{data:data}]});}
function drawDetail(chartId,width,height,all,dateX){var chart=new Highcharts.Chart({chart:{renderTo:'chart',type:'line',width:width,heihgt:height,backgroundColor:'#F6F7F8'},title:{text:'你的BPI',style:{color:'#000',fontWeight:'bold',fontFamily:'Microsoft YaHei'}},credits:{enabled:false},xAxis:{categories:dateX,labels:{rotation:45,y:40,style:{fontFamily:'Arial'}}},legend:{enabled:false},yAxis:{title:{text:''},gridLineColor:'#F6F7F8',labels:{formatter:function(){return this.value},style:{color:'orange'}}},tooltip:{crosshairs:true,shared:true},plotOptions:{line:{marker:{enabled:false,symbol:'circle'}},series:{cursor:'pointer',point:{events:{click:function(){}}}}},series:[{data:all[0],name:'BPI',color:'#000'}]});var tuIndexs=[];var tuIndex=0;var color='';tuIndexs[0]=tuIndex;$('#category-nav li').click(function(){var index=$(this).index();if(tuIndex<6&&tuIndexs[index]==undefined){tuIndexs[index]=++tuIndex;}
if(chart.series[tuIndexs[index]]==undefined){chart.addSeries({name:$(this).text(),data:all[index],color:$(this).attr('data-color')});$(this).addClass('current');color=$(this).attr('data-color');$(this).children('a').css('color',color);}else if($('.highcharts-tracker').find('path').eq(tuIndexs[index]).css('visibility')=='visible'){chart.series[tuIndexs[index]].hide();$(this).removeClass('current');$(this).children('a').css('color','#2181A9');}else{chart.series[tuIndexs[index]].show();$(this).addClass('current');color=$(this).attr('data-color');$(this).children('a').css('color',color);}
return false;});}
function drawLine(chartId,width,height,color){var chart=new Highcharts.Chart({chart:{renderTo:chartId,height:height,width:width,type:'line',backgroundColor:color,marginTop:25},title:{text:'训练三个月后',verticalAlign:'top',style:{color:'#666',fontSize:'12px'},x:150,y:30},subtitle:{text:'起始分数',verticalAlign:'bottom',align:'left',x:30,y:-50,style:{fontSize:'12px',color:'#666'}},credits:{enabled:false},legend:{enabled:false},xAxis:{title:{text:'训练天数',align:'high',style:{fontSize:'12px',fontWeight:'normal',color:'#666'}},categories:['0','20','40','60','80','100']},yAxis:{title:{text:'大脑性能指数',align:'high',offset:-46,x:-10,y:-10,rotation:0,style:{fontWeight:'normal',color:'#666'}},gridLineDashStyle:'dash',labels:{formatter:function(){return this.value},style:{color:'#666'}}},tooltip:{enabled:false},plotOptions:{series:{marker:{enabled:false,lineWidth:2,fillColor:'#fff',lineColor:null}}},series:[{data:[337.0,644,666,777,888.2,{y:1000,marker:{enabled:true}}],color:'#00A1F0'}]});}
function survey(next){var currentNum=parseInt($('#currentNum').text());var nextNum=(next===true)?currentNum+1:currentNum-1;var nextQuestion=$('#nextQuestion');var previousQuestion=$('#previousQuestion');var completeSurvey=$('#completeSurvey');nextQuestion.hide();previousQuestion.hide();completeSurvey.hide();$('.surveyhead'+currentNum).fadeOut('fast',function(){$('.surveyhead'+nextNum).fadeIn('fast');});$('#survey'+currentNum).fadeOut('fast',function(){$('#survey'+nextNum).fadeIn('fast');});$('#surveyexplan'+currentNum).fadeOut('fast',function(){$('#surveyexplan'+nextNum).fadeIn('fast');$('#currentNum').html(nextNum);if(next){if(currentNum<4){nextQuestion.show();previousQuestion.show();}else{previousQuestion.show();completeSurvey.show();}}else{if(currentNum>2){nextQuestion.show();previousQuestion.show();}else{nextQuestion.show();}}});}
function completeSurvey(){var result={};var cateCount=0;$(':checkbox').each(function(i){cateCount+=$(this).is(':checked')===true?1:0;if((i+1)%4===0){var _name=$(this).attr('name');result[_name]=cateCount;cateCount=0;}});$.ajax({url:'/course/survey',type:'POST',data:result,success:function(){window.location.href='/course';}});}
function showCourseGameover(data){$('.not-experience-result').show();$('.nextgame').show();$('.skipgame').hide();$('.course-gamesorder .active').css('completed');showResultData(data);}
function showNormalGameover(data){$('.not-experience-result').show();$('.playagain').show();$('#weibo-share').show();showResultData(data);}
function showExperienceGameover(data){$('.isexperience').show();$('#weibo-share').show();}
function showResultData(data){$('#top-scores').show();var topfive='';for(var i=0;i<data.topfive.length;i++){topfive+='<li><div class="order">'+(i+1)+'</div><div class="score">'+data.topfive[i].score+'</div><div class="date">'+data.topfive[i].day+'</div></li>';}
$('#topfivedata').html(topfive);$('.result-bubbles').html('+'+data.bubbles);$('.result-bubblesstatus').html(data.bubblesstatus);$('#result-gamename').html(data.gamename);if(data.bpi==0){var html='<div class="bpi-value"><span id="comesoon">BPI即将开启</span></a></div>';}else{var html='<div class="bpi-value">'+data.bpi+'</div>';if(data.bpichange!==0){var change=(data.bpichange>0)?'high':'low';html+='<div class="bpi-change '+change+'"><span class="sign"></span>'+data.bpichange+'</div>';}}
$('.result-bpi').html(html);}
function loadGame(flashvars,flashurl){var params={quality:"high",allowscriptaccess:"always",allowFullScreen:"true",AllowNetworking:"all",allowfullscreen:"true",scale:"noscale"};swfobject.embedSWF(flashurl,"game-canvas","640","520","9.0.0","swf/expressInstall.swf",flashvars,params);}
function completeGame(id,flag){if(Boolean(id)&&flag){$.ajax({url:'/gameover',type:'POST',data:{id:id},dataType:'json',error:function(){alert('可能由于登录超时引起的错误，请刷新页面后重试')},success:function(data){$('.gamearea').remove();$('.course-lesson-complete').show();$('#rankbar').css({"width":data.rate+'%'});$('.ranktip').html(data.rate+'%');$('#your-score .score').html(data.score);switch(data.status){case 0:showExperienceGameover(data);break;case 1:showNormalGameover(data);break;case 2:showCourseGameover(data);break;}
share(data.typename,data.gamename,data.score);}});}else{window.location.reload();};}
function getParamsOfShareWindow(width,height){return['toolbar=0,status=0,resizable=1,width='+width+',height='+height+',left=',(screen.width-width)/2,',top=',(screen.height-height)/2].join('');}
function share(typename,gamename,score){var title='我刚在爱海豚完成了【'+gamename+'】游戏,这是一款'+typename+'训练游戏，我在游戏中取得了'+score+'分!你敢来挑战我吗? http://www.aihaitun.com';thirdparty(title,false);}
function thirdparty(title,link){if(!link){link=encodeURIComponent(document.location);}
var source=encodeURIComponent('爱海豚');var windowName='share';$('#sina-share').click(function(){var appkey=2118089168,uid=2878188082;var url='http://service.weibo.com/share/share.php?&appkey='+appkey+'&title='+title+'&ralateUid='+uid;var params=getParamsOfShareWindow(800,600);window.open(url,windowName,params);});$('#qq-share').click(function(){var url='http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url='+link+'&title='+title+'&pics=';var params=getParamsOfShareWindow(800,600);window.open(url,windowName,params);});$('#renren-share').click(function(){var url='http://widget.renren.com/dialog/share?resourceUrl='+link+'&title='+title+'&pic=';var params=getParamsOfShareWindow(800,600);window.open(url,windowName,params);});$('#douban-share').click(function(){var url='http://www.douban.com/recommend/?url='+link+'&title='+title;var params=getParamsOfShareWindow(800,600);window.open(url,windowName,params);});$('#wangyi-share').click(function(){var params=getParamsOfShareWindow(800,600);var url='http://t.163.com/article/user/checkLogin.do?source=XEhus9eRe9d0ta7k&info='+title+'  '+link;window.open(url,windowName,params);});}
$(document).ready(function(){$('#nextQuestion').click(function(){survey(true);});$('#previousQuestion').click(function(){survey(false);});$('#completeSurvey').click(function(){completeSurvey();});$(function(){fnPlaceholder()});var fnPlaceholder=function(){if(!('placeholder'in document.createElement('input'))){$("input[placeholder],textarea[placeholder]").closest('form').has(':reset').bind('reset',function(){setTimeout(function(){$("input[placeholder],textarea[placeholder]").each(function(){$(this).val($(this).attr('placeholder')).addClass('ie-placeholder');})},0)})
$("input[placeholder],textarea[placeholder]").each(function(){$(this).val($(this).attr('placeholder')).addClass('ie-placeholder');}).bind('focus',function(){if($(this).val()==$(this).attr('placeholder')){$(this).val("").removeClass('ie-placeholder')}}).bind('blur',function(){if($(this).val().length==0){$(this).val($(this).attr('placeholder')).addClass('ie-placeholder')}})}}
$('input').iCheck({checkboxClass:'icheckbox_flat-red',radioClass:'iradio_flat-red'})
$("[rel='tooltip']").tooltip();});